version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: order-management-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photosi
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin --protocol=TCP -h 127.0.0.1 -P 3306 -uroot -proot ping"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 20s

  # gateway
  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5000:8080
    depends_on:
      mysql:
        condition: service_healthy
      provisioner-api:
        condition: service_started
      category-api:
        condition: service_started
      product-api:
        condition: service_started
      order-api:
        condition: service_started

  # provisioner-api
  provisioner-api:
    build: ./provisioner-api
    container_name: provisioner-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5001:8080
    depends_on:
      provisioner-migrator:
        condition: service_completed_successfully

  provisioner-migrator:
    build: ./provisioner-api
    command: ["dotnet", "OrderManagement.Provisioner.Api.dll", "--migrate-only"]
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      mysql:
        condition: service_healthy

  # category-api
  category-api:
    build: ./category-api
    container_name: category-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5002:8080
    depends_on:
      category-migrator:
        condition: service_completed_successfully

  category-migrator:
    build: ./category-api
    command: ["dotnet", "OrderManagement.Category.Api.dll", "--migrate-only"]
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      mysql:
        condition: service_healthy
      provisioner-migrator:
        condition: service_completed_successfully

  # product-api
  product-api:
    build: ./product-api
    container_name: product-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5003:8080
    depends_on:
      product-migrator:
        condition: service_completed_successfully

  product-migrator:
    build: ./product-api
    command: ["dotnet", "OrderManagement.Product.Api.dll", "--migrate-only"]
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      mysql:
        condition: service_healthy
      category-migrator:
        condition: service_completed_successfully

  # order-api
  order-api:
    build: ./order-api
    container_name: order-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ASPNETCORE_ENVIRONMENT: Docker
    ports:
      - 5004:8080
    depends_on:
      order-migrator:
        condition: service_completed_successfully

  order-migrator:
    build: ./order-api
    command: ["dotnet", "OrderManagement.Order.Api.dll", "--migrate-only"]
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    depends_on:
      mysql:
        condition: service_healthy
      product-migrator:
        condition: service_completed_successfully

# db-init
  db-init:
    image: mysql:8
    container_name: db-init
    depends_on:
      mysql:
        condition: service_healthy
      order-migrator:
        condition: service_completed_successfully
    volumes:
      - ./db/init:/init:ro
    entrypoint: ["/bin/sh", "/init/db-init.sh"]

  # stack-ready
  stack-ready:
    image: alpine
    depends_on:
      gateway:
        condition: service_started
    command: >
      sh -c "echo '';
            echo '🚀 PhotoSì Order Management successfully started';
            echo '📚 Swagger Gateway → http://localhost:5000/swagger';
            echo '';
            sleep 2"

# volumes
volumes:
  mysql_data: