name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target:
          - gateway
          - provisioner-api
          - order-api
          - category-api
          - product-api

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: false

      - name: Restore
        run: dotnet restore ${{ matrix.target }}

      - name: Build (Release)
        run: dotnet build ${{ matrix.target }} --no-restore --configuration Release

      - name: Test (Release)
        run: dotnet test ${{ matrix.target }} --no-build --configuration Release --verbosity normal